### ISSUE TITLE
First spindle is always deleted

### ISSUE THREAD

**Issue by jens-k** [medpsytuebingen/Matlab#5]
https://github.com/medpsytuebingen/Matlab/blob/7fc389296272117a47d8926fa69c78caab4b4de3/detectEvents.m#L533

I believe, this currently always kills the first spindle

if ~isempty(SpiBeginning) || ~isempty(SpiEnd) && SpiBeginning(1,1)==1 
means
"if there is a spindle beginning OR (there is a spindle end but it started at the epochs beginning)"

**Comment by NNiethard** [comment]
No it doesn't. Actually it will almost never do anything because the statement SpiBeginning(1,1)==1 will only be true if the spi threshol dis crossed exactly at the second datapoint in this particular NREMEpoch. But the statement can be deleted as it is unnecessary. Instead we need to exclude the detected SpiEnd if there is no corresponding SpiBeginning! That case will probably never happen but in case i fixed it.

**Comment by jens-k** [comment]
Yeah but && evaluates before ||, so as long as ~isempty(SpiBeginning) the statement will evaluate as true ("1 || 0 && 0" is evaluated as "1 || (0 && 0)" and thus true).

**Comment by NNiethard** [comment]
True... I changed it to  
if SpiEnd(1) < SpiBeginning(1) % ...or the beginning
       SpiEnd(:,1) = [];
end

**Comment by jens-k** [comment]
This is solved, right?
